apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - virtual-service.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: demo-portal
        namespace: demo-portal
      spec:
        template:
          spec:
            containers:
              - name: demo-portal
                resources:
                  requests:
                    cpu: 250m
                    memory: 512Mi
                  limits:
                    cpu: 1.5
                    memory: 2Gi
              - name: istio-proxy
                image: auto
                resources:
                  requests:
                    cpu: 50m
                    memory: 56Mi
                securityContext:
                  allowPrivilegeEscalation: false
    target:
      kind: Deployment
      name: demo-portal
      namespace: demo-portal
images:
  - name: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/demo-portal
    newTag: main-6bed4eec40aa9a1cbbd5e507a8b92a15f3d1a8d9-1751485462
