apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - virtual-service.yaml
  - ./federator
  - ./rshiny-dashboard
images:
  - name: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-federator
    newTag: main-cbc4fee8f673fdde3414a7f4169d6c3951d5eedc-1748364635
  - name: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-dashboard
    newTag: main-ab9b600d90bbdd1fd495386c90262d1362942c9f-1743436852
