apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: "on"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.4.1-alpine
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: redis-config-volume
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
            - name: redis-data
              mountPath: /data
          command: ["sh", "-c", "envsubst < /usr/local/etc/redis/redis.conf > /tmp/redis.conf && cat /tmp/redis.conf && redis-server /tmp/redis.conf"]
      volumes:
        - name: redis-config-volume
          configMap:
            name: redis-config
        - name: redis-data
          emptyDir: {}
