steps:
  - id: install
    name: 'node:22-alpine3.21'
    dir: transfer-outbound
    entrypoint: npm
    args: ['ci', '--no-optional']

  - id: check-types
    name: 'node:22-alpine3.21'
    dir: transfer-outbound
    entrypoint: npm
    args: ['run', 'typecheck']

  - id: run-tests
    name: 'node:22-alpine3.21'
    dir: transfer-outbound
    entrypoint: npm
    args: ['run', 'jest']

  - name: 'gcr.io/cloud-builders/docker'
    id: generate-image-name
    entrypoint: 'bash'
    dir: transfer-outbound
    args:
      - '-c'
      - |
        set -o errexit
        set -o pipefail
        set -o nounset

        service="iidi-transfer-outbound"

        branch="${BRANCH_NAME:-$(git rev-parse --abbrev-ref HEAD)}"
        short_sha="${COMMIT_SHA:-$(git rev-parse --short HEAD)}"
        echo "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/paradire/${service}:${branch}-${short_sha}-$(date +%s)" > /workspace/imagename

  - name: 'gcr.io/cloud-builders/docker'
    id: build-if-main
    entrypoint: 'bash'
    dir: transfer-outbound
    args:
      - '-c'
      - |
        set -o errexit
        set -o pipefail
        set -o nounset

        if [[ "$BRANCH_NAME" == "main" ]]; then
          image=$(cat /workspace/imagename)
          echo "Building Docker image: ${image}"
          docker build -t "${image}" -f ./Dockerfile .
        else
          echo "Skipping build: Not on 'main' branch"
          exit 0
        fi

  - name: 'gcr.io/cloud-builders/docker'
    id: push-if-main
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -o errexit
        set -o pipefail
        set -o nounset

        if [[ "$BRANCH_NAME" == "main" ]]; then
          image=$(cat /workspace/imagename)
          echo "Pushing Docker image: ${image}"
          docker push "${image}"
        else
          echo "Skipping push: Not on 'main' branch"
          exit 0
        fi

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
