steps:
  - id: install
    name: 'node:22-alpine3.21'
    dir: transfer-outbound
    entrypoint: npm
    args: ['ci', '--no-optional']

  - id: check-types
    name: 'node:22-alpine3.21'
    dir: transfer-outbound
    entrypoint: npm
    args: ['run', 'typecheck']

  - id: run-tests
    name: 'node:22-alpine3.21'
    dir: transfer-outbound
    entrypoint: npm
    args: ['run', 'jest']

  - id: build-and-push-if-main
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    dir: transfer-outbound
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          service_name="iidi-transfer-outbound"
          
          image_name="northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/paradire/${service_name}"
          latest_image_tag="${image_name}:latest"
          unique_image_tag="${image_name}:${BRANCH_NAME}-${COMMIT_SHA:-unknown_sha}-$(date +%s)"

          docker build -t "${latest_image_tag}" -t "${unique_image_tag}" -f ./Dockerfile.prod .

          docker push --all-tags "${unique_image_tag}"
        else
          exit 0
        fi

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
