steps:
  - id: 'Install dependencies'
    name: 'node:22-alpine3.21'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'ci:all'] # script in the root package.json which runs ci at the root and in each sub-project

  - id: 'Prettier check'
    name: 'node:22-alpine3.21'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'prettier']

  - id: 'Eslint check'
    name: 'node:22-alpine3.21'
    entrypoint: 'npm'
    dir: ./
    args: ['run', 'eslint:ci']

options:
  logging: CLOUD_LOGGING_ONLY
