version: '3.8'
name: iidi-test

services:
  # ========================
  # Gateway Service
  # ========================
  gateway:
    image: nginx:1.27.3
    networks:
      - gateway
      - host-loopback
    ports:
      - "127.0.0.1:8080:80"
    configs:
      - source: gateway.test.conf
        target: /etc/nginx/conf.d/default.conf

  # ========================
  # Ontario (ON) Services
  # ========================
  on-fhir-db:
    image: postgres:14.11-alpine
    networks:
      - on-fhir-db
    environment:
      POSTGRES_DB: hapi-fhir-db
      POSTGRES_USER: hapi-fhir-db
      POSTGRES_PASSWORD: local-dev-value
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hapi-fhir-db -d hapi-fhir-db']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  on-fhir:
    image: hapiproject/hapi:latest
    networks:
      - gateway
      - on-fhir-db
    environment:
      POSTGRES_DB: hapi-fhir-db
      POSTGRES_USER: hapi-fhir-db
      POSTGRES_PASSWORD: local-dev-value
      DB_PORT: 5432
      DB_HOST: on-fhir-db
      FHIR_SERVER_ADDRESS: http://gateway:80/on/fhir
    depends_on:
      on-fhir-db:
        condition: service_healthy

  on-bullmq-redis:
    image: redis:7.4.1-alpine
    networks:
      - on-bullmq-redis
    command: redis-server --requirepass local-dev-value

  on-transfer-outbound:
    image: node-dev:1.0
    networks:
      - gateway
      - on-bullmq-redis
    ports:
      - "3002:3000"
    environment:
      REDIS_HOST: on-bullmq-redis
      REDIS_PASSWORD: local-dev-value
      FHIR_URL: http://on-fhir:8080/fhir

  # ========================
  # British Columbia (BC) Services
  # ========================
  bc-fhir-db:
    image: postgres:14.11-alpine
    networks:
      - bc-fhir-db
    environment:
      POSTGRES_DB: hapi-fhir-db
      POSTGRES_USER: hapi-fhir-db
      POSTGRES_PASSWORD: local-dev-value
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hapi-fhir-db -d hapi-fhir-db']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  bc-fhir:
    image: hapiproject/hapi:latest
    networks:
      - gateway
      - bc-fhir-db
    environment:
      POSTGRES_DB: hapi-fhir-db
      POSTGRES_USER: hapi-fhir-db
      POSTGRES_PASSWORD: local-dev-value
      DB_PORT: 5432
      DB_HOST: bc-fhir-db
      FHIR_SERVER_ADDRESS: http://gateway:80/bc/fhir
    depends_on:
      bc-fhir-db:
        condition: service_healthy

  bc-bullmq-redis:
    image: redis:7.4.1-alpine
    networks:
      - bc-bullmq-redis
    command: redis-server --requirepass local-dev-value

  bc-transfer-outbound:
    image: node-dev:1.0
    networks:
      - gateway
      - bc-bullmq-redis
    ports:
      - "3004:3000"
    environment:
      REDIS_HOST: bc-bullmq-redis
      REDIS_PASSWORD: local-dev-value
      FHIR_URL: http://bc-fhir:8080/fhir

  # ========================
  # Test Container
  # ========================
  uj1-pt-pt:
    image: user-journey-1:0.0.2
    build:
      context: ./user-journey-tests/uj1-pt-pt/
    networks:
      - gateway
    environment:
      BC_OUTBOUND_URL: http://gateway:80/bc/outbound
      ON_OUTBOUND_URL: http://gateway:80/on/outbound
      BC_FHIR_URL: http://gateway:80/bc/fhir
      ON_FHIR_URL: http://gateway:80/on/fhir

# ========================
# Configurations
# ========================
configs:
  gateway.test.conf:
    content: |
      server {
          location /on/fhir/ {
              proxy_pass http://on-fhir:8080/fhir/;
          }
          location /bc/fhir/ {
              proxy_pass http://bc-fhir:8080/fhir/;
          }
          location /on/outbound/ {
              proxy_pass http://on-transfer-outbound:3000/;
          }
          location /bc/outbound/ {
              proxy_pass http://bc-transfer-outbound:3000/;
          }
      }

# ========================
# Networks
# ========================
networks:
  host-loopback:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: '127.0.0.1'
  gateway:
    driver: bridge
  on-fhir-db:
    driver: bridge
    internal: true
  on-bullmq-redis:
    driver: bridge
    internal: true
  bc-fhir-db:
    driver: bridge
    internal: true
  bc-bullmq-redis:
    driver: bridge
    internal: true