site_name: IIDI-Tech Documentation
theme:
  name: material
docs_dir: docs

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture/GCP Architecture/GCP-Architecture.md
      - IIDI Architecture Diagram: architecture/IIDI-Architecture-Diagram.png
      - User Journeys:
          - Journey 1: architecture/User-Journey-1/User-Journey-1.md
          - Journey 2: architecture/User-Journey-2/User-Journey-2.md
  - API Reference:
      - Data Aggregation API: api/aggregation.md
      - Federator API: api/federator.md
      - Synthesizer API: api/synthesizer.md
  - UI:
      - UI: ui/ui.md
