site_name: IIDI-Tech Documentation
theme:
  name: material
docs_dir: docs

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture/GCP-Architecture.md
      - User Journeys:
          - Journey 1: architecture/User-Journey-1.md
          - Journey 2: architecture/User-Journey-2.md
  - API Reference:
      - Data Aggregation API: api/aggregation.md
  - UI:
      -UI: ui/ui.md
  - Contributing: contributing.md
