steps:
  - id: install
    name: "node:22-alpine3.21"
    dir: federator
    entrypoint: npm
    args: ["ci", "--no-optional"]

  - id: check-types
    name: "node:22-alpine3.21"
    dir: federator
    entrypoint: npm
    args: ["run", "typecheck"]

  - id: run-tests
    name: "node:22-alpine3.21"
    dir: federator
    entrypoint: npm
    args: ["run", "jest"]

  - name: "gcr.io/cloud-builders/docker"
    id: generate-image-name
    entrypoint: "bash"
    dir: federator
    args:
      - "-c"
      - |
        set -o errexit
        set -o pipefail
        set -o nounset

        service="iidi-federator"

        # NOTE: $BRANCH_NAME etc aren't shell variables, they're a Cloudbuild substitution syntax.
        # Also important to note that they depend on the trigger source, and won't be set by default
        # if the build is triggered via the cli (`gcloud builds submit`) UNLESS the `--substitutions`
        # flag is used to set them manually
        image_name="northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/iidi/${service}:$BRANCH_NAME-$COMMIT_SHA-$(date +%s)"
        echo "Image name for this build (if pushed): ${image_name}"
        echo "${image_name}" > /workspace/imagename

  - name: "gcr.io/cloud-builders/docker"
    id: build-if-iidi-cobra
    entrypoint: "bash"
    dir: federator
    args:
      - "-c"
      - |
        set -o errexit
        set -o pipefail
        set -o nounset

        if [[ "$BRANCH_NAME" == "iidi-cobra" ]]; then
          image=$(cat /workspace/imagename)
          echo "Building Docker image: ${image}"
          docker build -t "${image}" -f ./Dockerfile .
        else
          echo "Skipping build: Not on 'main' branch"
          exit 0
        fi

  - name: "gcr.io/cloud-builders/docker"
    id: push-if-iidi-cobra
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -o errexit
        set -o pipefail
        set -o nounset

        if [[ "$BRANCH_NAME" == "iidi-cobra" ]]; then
          image=$(cat /workspace/imagename)
          echo "Pushing Docker image: ${image}"
          docker push "${image}"
        else
          echo "Skipping push: Not on 'main' branch"
          exit 0
        fi

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
