apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment
  namespace: bc
  labels:
    app: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: aggregator
        image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-aggregator:main-13d5000112355bc91a9d121863bab403c5166859-1741799214 # {"$imagepolicy": "flux-system:aggregation-server-bc"}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FHIR_URL
          value: "http://hapi-fhir-svc.bc.svc.cluster.local:8080/fhir"
        - name: AGGREGATION_INTERVAL
          value: "60"
        - name: PUBLIC_KEY_PATH
          value: "/secrets/public_key.pem"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
        volumeMounts:
        - name: public-key-volume
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: public-key-volume
        secret:
          secretName: aggregator-public-key
