apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment
  namespace: bc
  labels:
    app: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: aggregator
        image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-aggregator:main-969ef8a4b7a1893534c0adb881663a9a4b80beb8-1741381829 # {"$imagepolicy": "flux-system:aggregation-server-bc"}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FHIR_URL
          value: "http://hapi-fhir-svc.bc.svc.cluster.local:8080/fhir"
        - name: AGGREGATION_INTERVAL
          value: "60"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
