apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - aggregator-secret.enc.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: aggregator-deployment
        namespace: bc
      spec:
        template:
          spec:
            containers:
              - name: aggregator
                resources:
                  requests:
                    cpu: 250m
                    memory: 256Mi
                  limits:
                    cpu: 1.5
                    memory: 2Gi
              - name: istio-proxy
                image: auto
                resources:
                  requests:
                    cpu: 50m
                    memory: 56Mi
                securityContext:
                  allowPrivilegeEscalation: false
    target:
      kind: Deployment
      name: aggregator-deployment
      namespace: bc
