apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - virtual-service.yaml
  - ./hapi-fhir-server
  - ./patient-browser
  - ./aggregation-server
  - ./on-transfer
  - ./redis-server