# ======================================================
# 🛠️ FLUX KUSTOMIZATION FOR ONTARIO ENVIRONMENT
# ======================================================

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: on-environment
  namespace: flux-system
spec:
  path: ./k8s/on
  interval: 2m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: flux-system
  decryption:
    provider: sops

# ======================================================
# 📦 IMAGE REPOSITORIES
# ======================================================

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: aggregation-server-on
  namespace: flux-system
spec:
  image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-aggregator
  interval: 1m0s
  provider: gcp

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: patient-browser-on
  namespace: flux-system
spec:
  image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/patient-browser-iidi
  interval: 1m0s
  provider: gcp

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: transfer-inbound-on
  namespace: flux-system
spec:
  image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-transfer-inbound
  interval: 1m0s
  provider: gcp

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: transfer-outbound-on
  namespace: flux-system
spec:
  image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-transfer-outbound
  interval: 1m0s
  provider: gcp

# ======================================================
# 📋 IMAGE POLICIES
# ======================================================

# Aggregation Server Policy
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: aggregation-server-on
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: aggregation-server-on
  filterTags:
    extract: $ts
    pattern: ^main-[a-fA-F0-9]+-(?P<ts>.*)
  policy:
    numerical:
      order: asc

# Patient Browser Policy
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: patient-browser-on
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: patient-browser-on
  filterTags:
    extract: $ts
    pattern: ^main-[a-fA-F0-9]+-(?P<ts>.*)
  policy:
    numerical:
      order: asc

# Transfer Inbound Policy
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: transfer-inbound-on
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: transfer-inbound-on
  filterTags:
    extract: $ts
    pattern: ^main-[a-fA-F0-9]+-(?P<ts>.*)
  policy:
    numerical:
      order: asc

# Transfer Outbound Policy
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: transfer-outbound-on
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: transfer-outbound-on
  filterTags:
    extract: $ts
    pattern: ^main-[a-fA-F0-9]+-(?P<ts>.*)
  policy:
    numerical:
      order: asc

# ======================================================
# 🔄 IMAGE UPDATE AUTOMATIONS
# ======================================================

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: on-updater
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 5m
  update:
    strategy: Setters
    path: ./k8s/on
  git:
    checkout:
      ref:
        branch: "main"
    commit:
      author:
        name: fluxbot
        email: fluxcd@users.noreply.github.com
      messageTemplate: "[ci skip] Updated Ontario environment images to {{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: "main"
