apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
  data:
  - secretKey: githubAppID
    remoteRef:
      key: argocd-github-auth-app-id
  - secretKey: githubAppInstallationID
    remoteRef:
      key: argocd-github-auth-app-installation-id
  - secretKey: githubAppPrivateKey
    remoteRef:
      key: argocd-github-auth-app-private-key