apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis-deployment.yaml
  - redis-service.yaml
  - redis-secret.enc.yaml
  - redis-config.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: redis
        namespace: bc
      spec:
        template:
          spec:
            containers:
              - name: redis
                resources:
                  requests:
                    cpu: 250m
                    memory: 512Mi
                  limits:
                    cpu: 1
                    memory: 2Gi
              - name: istio-proxy
                image: auto
                resources:
                  requests:
                    cpu: 50m
                    memory: 56Mi
                securityContext:
                  allowPrivilegeEscalation: false
    target:
      kind: Deployment
      name: redis
      namespace: bc
