apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: "bc"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.4.1-alpine
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          command:
            - /bin/sh
            - -c
            - |
              echo "redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT} --loglevel notice" > /tmp/run.sh && chmod +x /tmp/run.sh && /tmp/run.sh
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}