apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    namespace: bc
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:CJbIP5i5KIm0qmyPEtCkzW166cbr0Evk8mNloA==,iv:Bv1AS4QK82OvBezOyhvOGe3wbnnFpWJMliVU73ZxHVw=,tag:lUHYHumyxqcCgwyM9nW6bQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/phx-01he5rx4wsv/locations/northamerica-northeast1/keyRings/iidi-redis-secret/cryptoKeys/iidi-redis-secret
          created_at: "2025-03-10T22:01:48Z"
          enc: CiQAxKHEzqqOdTzf4zFlL+Qylb5xOtsFLl3RWz76lW38NUr+u28SSQAoSs8utra8IHlIBB9G79h5zqjrOM1G6tQtZzrFuqGQ+kfJ3mxfQ58JU289pBp0eM+/o1Hl6Fg7G5ZPSOUa7LN/8iATabS/bzg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-10T22:01:49Z"
    mac: ENC[AES256_GCM,data:BaaqINvxTOS1+61b8XLlnsf5iifq9E91HnC5ZeH3FhSeaHkPVT0TB3ONHBZdVM1q/E05E7FXHxDYUT8I3N4vL47gx7l/fpvXrRqbbZG/iSAzEdYLTbtSaaNxyMykas8ohBDpB4ak+GrCqCtjVlYkb7i1g4NZMJwGQEUSDg/z5Rk=,iv:c4PKq44VedPZRxObEJBnMROqfbz159Virjf99+6gikw=,tag:LMxqJ4iu2Nvg3FKhWfy8vA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
