---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hapi-fhir-server-bc
  namespace: flux-system
spec:
  path: ./k8s/bc/hapi-fhir-server
  interval: 2m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: cnpg-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aggregation-server-bc
  namespace: flux-system
spec:
  path: ./k8s/bc/aggregation-server
  interval: 2m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: hapi-fhir-server-bc

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: patient-browser-bc
  namespace: flux-system
spec:
  path: ./k8s/bc/patient-browser
  interval: 2m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: hapi-fhir-server-bc