apiVersion: v1
kind: Service
metadata:
  name: aggregation-server-on-svc
  labels:
    app: aggregation-server-on
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: aggregation-server-on