apiVersion: v1
kind: Service
metadata:
  name: demo-portal
  namespace: cobra
  annotations:
    argocd.argoproj.io/sync-wave: "42"
spec:
  selector:
    app: demo-portal
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
