apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    # List of container images to track via Argo CD Image Updater
    argocd-image-updater.argoproj.io/image-list: |
      aggregator=northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-aggregator
      patient-browser=northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/patient-browser-iidi
      transfer-inbound=northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-transfer-inbound
      transfer-outbound=northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-transfer-outbound
      synthetic-data=northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/synthetic-data

    # Git write-back configuration
    argocd-image-updater.argoproj.io/write-back-method: git:secret
    argocd-image-updater.argoproj.io/git-branch: iidi/argocd-integration

    # Update strategy and tag filtering per image
    argocd-image-updater.argoproj.io/aggregator.update-strategy: newest-build
    argocd-image-updater.argoproj.io/aggregator.allow-tags: regexp:^main-[a-fA-F0-9]+-(?P<ts>.*)

    argocd-image-updater.argoproj.io/patient-browser.update-strategy: newest-build
    argocd-image-updater.argoproj.io/patient-browser.allow-tags: regexp:^main-[a-fA-F0-9]+-(?P<ts>.*)

    argocd-image-updater.argoproj.io/transfer-inbound.update-strategy: newest-build
    argocd-image-updater.argoproj.io/transfer-inbound.allow-tags: regexp:^main-[a-fA-F0-9]+-(?P<ts>.*)

    argocd-image-updater.argoproj.io/transfer-outbound.update-strategy: newest-build
    argocd-image-updater.argoproj.io/transfer-outbound.allow-tags: regexp:^main-[a-fA-F0-9]+-(?P<ts>.*)

    argocd-image-updater.argoproj.io/synthetic-data.update-strategy: newest-build
    argocd-image-updater.argoproj.io/synthetic-data.allow-tags: regexp:^main-[a-fA-F0-9]+-(?P<ts>.*)

spec:
  project: default
  source:
    repoURL: https://github.com/PHACDataHub/iidi-tech.git
    targetRevision: iidi/argocd-integration
    path: k8s/bc
  destination:
    server: https://kubernetes.default.svc
    namespace: bc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true