apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-portal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    # Image tracking for Argo CD Image Updater
    argocd-image-updater.argoproj.io/image-list: |
      demo-portal=northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/demo-portal

    # Git write-back settings
    argocd-image-updater.argoproj.io/write-back-method: git:secret
    argocd-image-updater.argoproj.io/git-branch: iidi/argocd-integration

    # Update strategy and tag regex filtering
    argocd-image-updater.argoproj.io/demo-portal.update-strategy: latest
    argocd-image-updater.argoproj.io/demo-portal.allow-tags: regexp:^main-[a-fA-F0-9]+-(?P<ts>.*)
spec:
  project: default
  source:
    repoURL: https://github.com/PHACDataHub/iidi-tech.git
    targetRevision: iidi/argocd-integration
    path: demo-portal
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-portal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
