apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-updater
  namespace: argocd
  annotations:
    iam.gke.io/gcp-service-account: flux-image-puller@phx-01he5rx4wsv.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-repo-server
  namespace: argocd
  annotations:
    iam.gke.io/gcp-service-account: sops-kms@phx-01he5rx4wsv.iam.gserviceaccount.com
