apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-browser
  namespace: bc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-browser
  template:
    metadata:
      labels:
        app: patient-browser
        version: v1
    spec:
      containers:
      - name: patient-browser
        image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/patient-browser-iidi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PT # TODO: delete in favour of FHIR_URL once new patient-browser docker images are pushed 
          value: "bc"
        - name: FHIR_URL
          value: "https://fhir.bc.iidi.alpha.phac.gc.ca/fhir"
