apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-browser
  namespace: bc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-browser
  template:
    metadata:
      labels:
        app: patient-browser
        version: v1
    spec:
      containers:
      - name: patient-browser
        image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/patient-browser-iidi:main-153c34381ef0bca44116c9b7ccd9619934b93fc7-1739905750 # {"$imagepolicy": "flux-system:patient-browser-bc"}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: FHIR_URL
          value: "https://fhir.bc.iidi.alpha.phac.gc.ca/fhir"
