apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# IIDI Application for Cobra Tenant
# All resources deploy to cobra namespace managed by platform

# Set namespace for all resources
namespace: cobra

resources:
  # Security - External Secrets (sync-wave: 20)
  - security/external-secrets.yaml

  # Gateway API - HTTPRoutes (sync-wave: 70)
  - gateway/httproutes.yaml


  # BC Services
  - bc-services/hapi-fhir-server/configmap.yaml # sync-wave: 20
  - bc-services/hapi-fhir-server/deployment.yaml # sync-wave: 30
  - bc-services/hapi-fhir-server/service.yaml # sync-wave: 30
  - bc-services/hapi-fhir-server/synthetic-data.yaml

  - bc-services/redis-server/
  - bc-services/patient-browser/
  - bc-services/aggregation-server/
  - bc-services/bc-transfer/

  # ON Services
  - on-services/hapi-fhir-server/configmap.yaml
  - on-services/hapi-fhir-server/deployment.yaml 
  - on-services/hapi-fhir-server/service.yaml
  - on-services/hapi-fhir-server/synthetic-data.yaml
  - on-services/redis-server/
  - on-services/patient-browser/
  - on-services/aggregation-server/
  - on-services/on-transfer/

  # Federal Services
  - federal-services/federator/
  - federal-services/rshiny-dashboard/

  # Demo Services
  - demo-services/demo-portal/
  - demo-services/demo-transfer-dashboard/

  # Networking (sync-wave: 45-50)
  - networking/network-policies.yaml

# Common labels applied to all resources
labels:
- pairs:
    tenant: cobra
    app.kubernetes.io/managed-by: argocd

# Global annotations
commonAnnotations:
  app.kubernetes.io/version: "1.0.0"

# Image transformations - update to use Artifact Registry
images:
  # HAPI FHIR Server
  - name: hapiproject/hapi
    newName: northamerica-northeast1-docker.pkg.dev/gcdm022b-cobra/iidi/hapi
    newTag: v7.6.0

  # Redis
  - name: redis
    newName: northamerica-northeast1-docker.pkg.dev/gcdm022b-cobra/iidi/redis
    newTag: 7-alpine

# Patches to apply
patches:
  # Add service account to all deployments
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-important
      spec:
        template:
          spec:
            serviceAccountName: cobra-app-sa
