# External Secrets for IIDI Application in Cobra Tenant
# BC Redis Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-bc-secret
  labels:
    gc.ca/data-classification: unclassified
    gc.ca/environment: dev
    gc.ca/tier: tier3
    tenant: cobra
    app.kubernetes.io/part-of: iidi
    app.kubernetes.io/component: external-secret
    province: bc
  annotations:
    config.sync.gke.io/sync-wave: "20"
spec:
  secretStoreRef:
    name: cobra-secret-store
    kind: SecretStore
  target:
    name: redis-bc-secret
    creationPolicy: Owner
  data:
  - secretKey: redis-password
    remoteRef:
      key: cobra-redis-bc-password

---
# ON Redis Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-on-secret
  labels:
    gc.ca/data-classification: unclassified
    gc.ca/environment: dev
    gc.ca/tier: tier3
    tenant: cobra
    app.kubernetes.io/part-of: iidi
    app.kubernetes.io/component: external-secret
    province: on
  annotations:
    config.sync.gke.io/sync-wave: "20"
spec:
  secretStoreRef:
    name: cobra-secret-store
    kind: SecretStore
  target:
    name: redis-on-secret
    creationPolicy: Owner
  data:
  - secretKey: redis-password
    remoteRef:
      key: cobra-redis-on-password

---
# Federal Federator Key Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: federator-key-secret
  labels:
    gc.ca/data-classification: unclassified
    gc.ca/environment: dev
    gc.ca/tier: tier3
    tenant: cobra
    app.kubernetes.io/part-of: iidi
    app.kubernetes.io/component: external-secret
  annotations:
    config.sync.gke.io/sync-wave: "20"
spec:
  secretStoreRef:
    name: cobra-secret-store
    kind: SecretStore
  target:
    name: federator-key-secret
    creationPolicy: Owner
  data:
  - secretKey: federator-key
    remoteRef:
      key: cobra-federator-key

---
# BC Aggregator Key Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aggregator-bc-key-secret
  labels:
    gc.ca/data-classification: unclassified
    gc.ca/environment: dev
    gc.ca/tier: tier3
    tenant: cobra
    app.kubernetes.io/part-of: iidi
    app.kubernetes.io/component: external-secret
    province: bc
  annotations:
    config.sync.gke.io/sync-wave: "20"
spec:
  secretStoreRef:
    name: cobra-secret-store
    kind: SecretStore
  target:
    name: aggregator-bc-key-secret
    creationPolicy: Owner
  data:
  - secretKey: aggregator-key
    remoteRef:
      key: cobra-aggregator-bc-key

---
# ON Aggregator Key Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aggregator-on-key-secret
  labels:
    gc.ca/data-classification: unclassified
    gc.ca/environment: dev
    gc.ca/tier: tier3
    tenant: cobra
    app.kubernetes.io/part-of: iidi
    app.kubernetes.io/component: external-secret
    province: on
  annotations:
    config.sync.gke.io/sync-wave: "20"
spec:
  secretStoreRef:
    name: cobra-secret-store
    kind: SecretStore
  target:
    name: aggregator-on-key-secret
    creationPolicy: Owner
  data:
  - secretKey: aggregator-key
    remoteRef:
      key: cobra-aggregator-on-key