apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: phx-01he5rx4wsv
      auth:
        workloadIdentity:
          clusterLocation: northamerica-northeast1
          clusterName: iidi-cluster
          serviceAccountRef:
            name: eso-sa
            namespace: default
