apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-sa
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: eso-gcp-reader@phx-01he5rx4wsv.iam.gserviceaccount.com
    argocd.argoproj.io/sync-wave: "0"
