apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - eso-service-account.yaml              # Manually managed SA with GCP IAM annotation
  - cluster-secret-store.yaml            # Your ClusterSecretStore pointing to eso-sa
  - external-secrets-store.yaml          # Includes all CRDs and any ExternalSecrets or SecretStores

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.17.0
    releaseName: external-secrets
    namespace: external-secrets
    valuesInline:
      installCRDs: false                  # You're applying CRDs manually
      serviceAccount:
        create: false                    # You're creating it manually
        name: eso-sa
