namespace: argocd

resources:
  - image-updater.yaml
  - git-creds.yaml

patchesJson6902:
  # Patch the ServiceAccount for GCP Workload Identity
  - target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: argocd-image-updater
      namespace: argocd
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          iam.gke.io/gcp-service-account: argocd-image-updater@phx-01he5rx4wsv.iam.gserviceaccount.com