apiVersion: apps/v1
kind: Deployment
metadata:
  name: on-bullmq-redis
  namespace: "on"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bullmq-redis
  template:
    metadata:
      labels:
        app: bullmq-redis
    spec:
      containers:
        - name: redis
          image: redis:7.4.1-alpine
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)", "--port", "$(REDIS_PORT)", "--loglevel", "notice"]
