apiVersion: v1
kind: Service
metadata:
  name: transfer-inbound-svc
  namespace: "on"
  labels:
    app: transfer-inbound
spec:
  selector:
    app: transfer-inbound
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
