apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-inbound
  namespace: "on"
  labels:
    app: transfer-inbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-inbound
  template:
    metadata:
      labels:
        app: transfer-inbound
    spec:
      containers:
        - name: transfer-inbound
          image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-transfer-inbound:main-1806507b56ade6b634b181c2c752c2adc290e2ef-1740676482 # {"$imagepolicy": "flux-system:transfer-inbound-on"}
          ports:
            - containerPort: 3000
          env:
            - name: EXPRESS_PORT
              value: "3000"
            - name: DEV_IS_LOCAL_ENV
              value: "false"
            - name: FHIR_URL
              value: "http://hapi-fhir-svc.on.svc.cluster.local:8080/fhir"
