apiVersion: v1
kind: Service
metadata:
  name: transfer-inbound-bc-svc
  namespace: cobra
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app: transfer-inbound-bc
spec:
  selector:
    app: transfer-inbound-bc
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
