apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-browser-on
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-browser-on
  template:
    metadata:
      labels:
        app: patient-browser-on
        version: v1
    spec:
      containers:
        - name: patient-browser-on
          image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/iidi/patient-browser-iidi:main-153c34381ef0bca44116c9b7ccd9619934b93fc7-1739905750
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: FHIR_URL
              value: "http://hapi-fhir-on-svc.cobra.svc.cluster.local:8080/fhir"
