apiVersion: v1
kind: Service
metadata:
  name: patient-browser-on-svc
spec:
  type: ClusterIP
  ports:
  - name: http-patient
    port: 8079
    targetPort: 80
    protocol: TCP
  selector:
    app: patient-browser-on
