apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - transfer-inbound.yaml
  - transfer-outbound.yaml
  - transfer-inbound-service.yaml
  - transfer-outbound-service.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: transfer-inbound-on
      spec:
        template:
          spec:
            containers:
              - name: transfer-inbound-on
                resources:
                  requests:
                    cpu: 250m
                    memory: 256Mi
                  limits:
                    cpu: 1.5
                    memory: 2Gi
              - name: istio-proxy
                image: auto
                resources:
                  requests:
                    cpu: 50m
                    memory: 56Mi
                securityContext:
                  allowPrivilegeEscalation: false
    target:
      kind: Deployment
      name: transfer-inbound

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: transfer-outbound-on
      spec:
        template:
          spec:
            containers:
              - name: transfer-outbound-on
                resources:
                  requests:
                    cpu: 250m
                    memory: 256Mi
                  limits:
                    cpu: 1.5
                    memory: 2Gi
              - name: istio-proxy
                image: auto
                resources:
                  requests:
                    cpu: 50m
                    memory: 56Mi
                securityContext:
                  allowPrivilegeEscalation: false
    target:
      kind: Deployment
      name: transfer-outbound
