apiVersion: v1
kind: Service
metadata:
  namespace: cobra
  name: transfer-outbound-on-svc
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app: transfer-outbound-on
spec:
  selector:
    app: transfer-outbound-on
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
