apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - database.yaml
  - deployment.yaml
  - service.yaml
  # - synthetic-data.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hapi-fhir-server-on
      spec:
        template:
          spec:
            containers:
              - name: hapi-fhir-server-on
                resources:
                  requests:
                    cpu: 2
                    memory: 4Gi
                  limits:
                    cpu: 4
                    memory: 8Gi
              - name: istio-proxy
                image: auto
                resources:
                  requests:
                    cpu: 50m
                    memory: 56Mi
                securityContext:
                  allowPrivilegeEscalation: false
    target:
      kind: Deployment
      name: hapi-fhir-server-on
