apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    app: hapi-fhir-on-svc
  name: hapi-fhir-on-svc
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http-server 
  selector:
    app: hapi-fhir-server-on
status:
  loadBalancer: {}