apiVersion: v1
kind: Service
metadata:
  namespace: cobra
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app: hapi-fhir-on-svc
  name: hapi-fhir-on-svc
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http 
  selector:
    app: hapi-fhir-server-on
