apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - transfer-inbound.yaml
  - transfer-outbound.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - redis-secret.enc.yaml
  - transfer-inbound-service.yaml
  - transfer-outbound-service.yaml