apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-outbound
  namespace: "bc"
  labels:
    app: transfer-outbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-outbound
  template:
    metadata:
      labels:
        app: transfer-outbound
    spec:
      containers:
        - name: transfer-outbound
          image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-transfer-outbound:main-0c2fc2901f7023705c0272b126132fdf3eb4234d-1741880518 # {"$imagepolicy": "flux-system:transfer-outbound-bc"}
          ports:
            - containerPort: 3000
          env:
            - name: EXPRESS_PORT
              value: "3000"
            - name: DEV_IS_LOCAL_ENV
              value: "false"
            - name: REDIS_HOST
              value: "redis.bc.svc.cluster.local"
            - name: FHIR_URL
              value: "http://hapi-fhir-svc.bc.svc.cluster.local:8080/fhir"
            - name: OWN_TRANSFER_CODE
              value: "BC"
            - name: INBOUND_TRANSFER_SERIVCES_BY_TRANSFER_CODE
              value: '{ "ON": "http://transfer-inbound-svc.on.svc.cluster.local:3000" }'
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: TRANSFER_DASHBOARD_ORIGINS
              value: "https://demo-transfer-dashboard.iidi.alpha.phac.gc.ca,http://localhost:8080,http://localhost:3000,http://localhost:3005"
