apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-outbound-bc
  namespace: "bc"
  labels:
    app: transfer-outbound-bc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-outbound-bc
  template:
    metadata:
      labels:
        app: transfer-outbound-bc
    spec:
      containers:
        - name: transfer-outbound-bc
          image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/patient-browser-iidi:main-153c34381ef0bca44116c9b7ccd9619934b93fc7-1739905750 # {"$imagepolicy": "flux-system:patient-browser-bc"}
          ports:
            - containerPort: 3000
          env:
            - name: EXPRESS_PORT
              value: "3000"
            - name: DEV_IS_LOCAL_ENV
              value: "True"
            - name: REDIS_HOST
              value: "on-bullmq-redis"
            - name: FHIR_URL
              value: "http://hapi-fhir-svc.on.svc.cluster.local:8080/fhir"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
