apiVersion: v1
kind: Service
metadata:
  name: transfer-outbound-svc
  namespace: "bc"
  labels:
    app: transfer-outbound
spec:
  selector:
    app: transfer-outbound
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
