apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-inbound
  namespace: "bc"
  labels:
    app: transfer-inbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-inbound
  template:
    metadata:
      labels:
        app: transfer-inbound
    spec:
      containers:
        - name: transfer-inbound
          image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-transfer-inbound:main-b955509c2163aa91cc6cd6a679d8415028aa5285-1741625533 # {"$imagepolicy": "flux-system:transfer-inbound-bc"}
          ports:
            - containerPort: 3000
          env:
            - name: EXPRESS_PORT
              value: "3000"
            - name: DEV_IS_LOCAL_ENV
              value: "false"
            - name: FHIR_URL
              value: "http://hapi-fhir-svc.bc.svc.cluster.local:8080/fhir"
