apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-inbound-bc
  namespace: "on"
  labels:
    app: transfer-inbound-bc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-inbound-bc
  template:
    metadata:
      labels:
        app: transfer-inbound-bc
    spec:
      containers:
        - name: transfer-inbound-bc
          image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-transfer-inbound:main-bedc8be470fbea3aeba1cbe574e5504204f4bcf3-1739982587 # {"$imagepolicy": "flux-system:patient-browser-bc"}
          ports:
            - containerPort: 3000
          env:
            - name: EXPRESS_PORT
              value: "3000"
            - name: DEV_IS_LOCAL_ENV
              value: "True"
            - name: FHIR_URL
              value: "http://hapi-fhir-svc.on.svc.cluster.local:8080/fhir"
