apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hapi-fhir-db-bc
  labels:
    app: hapi-fhir-db-bc
    gc.ca/data-classification: unclassified
    gc.ca/environment: dev
    gc.ca/tier: tier3
    tenant: cobra
    app.kubernetes.io/part-of: iidi
    app.kubernetes.io/component: database
    province: bc
  annotations:
    config.sync.gke.io/sync-wave: "10"
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:14.11
  instances: 2
  enablePDB: true  
  startDelay: 900
  stopDelay: 900
  primaryUpdateStrategy: unsupervised

# PostGres Best Practices for the Logging 
  #  - https://www.enterprisedb.com/blog/how-get-best-out-postgresql-logs
  #  - https://medium.com/google-cloud/correlate-statement-logs-in-cloudsql-for-postgres-with-connection-sessions-5bae4ade38f5
  #  - PostgreSQL Official Documentation on pg_stat_statements: https://www.postgresql.org/docs/current/pgstatstatements.html
  #  - pgAudit GitHub Repository: https://github.com/pgaudit/pgaudit
  postgresql:
    parameters:
      log_min_messages: "warning" # From "error" to "warning" to reduce informational messages
      pg_stat_statements.track: top # From "all" to "top" to only track top-level statements
      auto_explain.log_min_duration: '30s' # From "10s" to "30s" to reduce slow query logs
      pgaudit.log: "none"
      log_connections: "off" # Reduced connection logs
      log_disconnections: "off" # Reduced disconnection logs
      log_hostname: "off" # Avoided logging hostnames
      log_temp_files: "1024" # Log temp files larger than 1MB
      log_lock_waits: "on" # Keep "on" if monitoring for lock waits
      log_checkpoints: "on" # Keep "on" for checkpointing information
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
    pg_hba:
      - host all all all md5

  bootstrap:
    initdb:
      database: hapi-fhir-db-bc
      owner: hapi-fhir-db-bc

  storage:
    storageClass: standard
    size: 5Gi

  nodeMaintenanceWindow:
    inProgress: true
    reusePVC: true

  inheritedMetadata:
    annotations:
      proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      sidecar.istio.io/proxyCPU: 50m
      sidecar.istio.io/proxyMemory: 56Mi

  resources:
    requests:
      cpu: 100m
      memory: 1024Mi
    limits:
      cpu: 500m
      memory: 2.5Gi      