apiVersion: v1
kind: Service
metadata:
  labels:
    app: hapi-fhir-bc-svc
    gc.ca/data-classification: unclassified
    gc.ca/environment: dev
    gc.ca/tier: tier3
    tenant: cobra
    app.kubernetes.io/part-of: iidi
    app.kubernetes.io/component: fhir-service
    province: bc
  name: hapi-fhir-bc-svc
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http 
  selector:
    app: hapi-fhir-server-bc