apiVersion: batch/v1
kind: Job
metadata:
  name: synthetic-data-job-bc
  namespace: cobra
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    argocd.argoproj.io/sync-options: "Replace=false"
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccountName: cobra-app-sa
      restartPolicy: Never
      containers:
        - name: synthetic-data
          image: northamerica-northeast1-docker.pkg.dev/gcdm022b-cobra/iidi/synthetic-data:main-01df63e5bec99369feefd606f28e4db267f7716c-1741382883
          imagePullPolicy: Always
          env:
            - name: NUM_RECORDS
              value: "500"
            - name: PT
              value: "bc"
            - name: FHIR_URL
              value: "http://hapi-fhir-bc-svc.cobra.svc.cluster.local:8080/fhir"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
