apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patches:
  # Minimum resource requests for controllers
  - target:
      kind: Deployment
      name: "(kustomize-controller|source-controller|image-reflector-controller|image-automation-controller|notification-controller|helm-controller)"
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  requests:
                    cpu: 50m
                    memory: 100Mi
                  limits:
                    cpu: 150m
                    memory: 300Mi

  # Patch image-reflector-controller service account to access artifact registry
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: image-reflector-controller
        namespace: flux-system
        annotations:
          iam.gke.io/gcp-service-account: flux-image-puller@phx-01he5rx4wsv.iam.gserviceaccount.com
    target:
      kind: ServiceAccount
      name: image-reflector-controller

  # Patch kustomize-controller service account to access SOPS KMS
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kustomize-controller
        namespace: flux-system
        annotations:
          iam.gke.io/gcp-service-account: sops-kms@phx-01he5rx4wsv.iam.gserviceaccount.com
    target:
      kind: ServiceAccount
      name: kustomize-controller
