apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-browser
  namespace: "on"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-browser
  template:
    metadata:
      labels:
        app: patient-browser
        version: v1
    spec:
      containers:
      - name: patient-browser
        image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/patient-browser-iidi:master-08636a0-1739817575 # {"$imagepolicy": "flux-system:patient-browser-on"}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: FHIR_URL
          value: "https://fhir.on.iidi.alpha.phac.gc.ca/fhir"
