apiVersion: apps/v1
kind: Deployment
metadata:
  name: federator-deployment
  namespace: cobra
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app: federator
    app.kubernetes.io/name: federator
    app.kubernetes.io/component: federal-services
    app.kubernetes.io/part-of: iidi-tech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: federator
  template:
    metadata:
      labels:
        app: federator
        app.kubernetes.io/name: federator
        app.kubernetes.io/component: federal-services
        app.kubernetes.io/part-of: iidi-tech
    spec:
      containers:
      - name: federator
        image: northamerica-northeast1-docker.pkg.dev/gcdm022b-cobra/iidi/iidi-federator:main-13d5000112355bc91a9d121863bab403c5166859-1741799249
        ports:
        - containerPort: 3000
        env:
        - name: DEV_IS_LOCAL_ENV
          value: "false"
        - name: AGGREGATOR_URLS
          value: "http://aggregation-server-on-svc.cobra.svc.cluster.local,http://aggregation-server-bc-svc.cobra.svc.cluster.local"
        - name: PRIVATE_KEY_PATH
          value: "/secrets/private_key.pem"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: private-key-volume
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: private-key-volume
        secret:
          secretName: federator-private-key
