apiVersion: v1
kind: Service
metadata:
  name: federator-svc
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app: federator
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: federator