apiVersion: v1
kind: Service
metadata:
  name: federator-svc
  namespace: cobra
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app: federator
    app.kubernetes.io/name: federator
    app.kubernetes.io/component: federal-services
    app.kubernetes.io/part-of: iidi-tech
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: federator