apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aggregator-public-key
  namespace: "on"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: aggregator-public-key
    creationPolicy: Owner
  data:
    - secretKey: public_key.pem
      remoteRef:
        key: aggregator-public-key-on
        version: latest
