apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment
  namespace: "on"
  labels:
    app: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: aggregator
        image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-aggregator:main-1d86a67eaa3c4fec558ce699d674583bb82a731b-1741131811 # {"$imagepolicy": "flux-system:aggregation-server-on"}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FHIR_URL
          value: "http://hapi-fhir-svc.on.svc.cluster.local:8080/fhir"
        - name: AGGREGATION_INTERVAL
          value: "60"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3
