apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment
  namespace: "on"
  labels:
    app: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: aggregator
        image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/iidi-aggregator:main-d891015e7f600579f23718fede53eab3bea9587c-1741875207 # {"$imagepolicy": "flux-system:aggregation-server-on"}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FHIR_URL
          value: "http://hapi-fhir-svc.on.svc.cluster.local:8080/fhir"
        - name: AGGREGATION_INTERVAL
          value: "60"
        - name: PUBLIC_KEY_PATH
          value: "/secrets/public_key.pem"
        - name: IS_LOCAL_DEV
          value: "false"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
        volumeMounts:
        - name: public-key-volume
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: public-key-volume
        secret:
          secretName: aggregator-public-key
