apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  namespace: "on"
  labels:
    app: aggregator
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: aggregator