apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation-server-bc-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "35"
  labels:
    app: aggregation-server-bc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregation-server-bc
  template:
    metadata:
      labels:
        app: aggregation-server-bc
    spec:
      containers:
      - name: aggregation-server-bc
        image: northamerica-northeast1-docker.pkg.dev/gcdm022b-cobra/iidi/iidi-aggregator:main-e8cfd8306b4e4c2c55c3d532469fc7d18b7ba671-1741876097
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FHIR_URL
          value: "http://hapi-fhir-bc-svc.cobra.svc.cluster.local:8080/fhir"
        - name: AGGREGATION_INTERVAL
          value: "60"
        - name: PUBLIC_KEY_PATH
          value: "/secrets/public_key.pem"
        - name: IS_LOCAL_DEV
          value: "false"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
        volumeMounts:
        - name: public-key-volume
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: public-key-volume
        secret:
          secretName: aggregation-server-bc-public-key
