apiVersion: v1
kind: Service
metadata:
  name: aggregation-server-bc-svc
  annotations:
    argocd.argoproj.io/sync-wave: "35"
  labels:
    app: aggregation-server-bc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: aggregation-server-bc