apiVersion: v1
kind: Service
metadata:
  labels:
    app: hapi-fhir-svc
  name: hapi-fhir-svc
  namespace: "on"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http-server 
  selector:
    app: hapi-fhir-server
status:
  loadBalancer: {}