apiVersion: v1
kind: Service
metadata:
  name: redis-bc
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  selector:
    app: redis-bc
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
