apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-bc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-bc
  template:
    metadata:
      labels:
        app: redis-bc-bc
    spec:
      volumes:
        - name: redis-config-volume
          configMap:
            name: redis-config-bc
        - name: redis-data
          emptyDir: {}

      containers:
        - name: redis
          image: redis:7.4.1-alpine
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-bc-secret
                  key: redis-password
          command:
            - /bin/sh
            - -c
            - |
              echo "Starting Redis with a secure configuration..."
              sed "s|\${REDIS_PASSWORD}|${REDIS_PASSWORD}|g" /redis-config/redis.conf > /data/redis-final.conf
              redis-server /data/redis-final.conf
          volumeMounts:
            - name: redis-config-volume
              mountPath: /redis-config
            - name: redis-data
              mountPath: /data
