apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret-on
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cobra-secret-store
    kind: SecretStore
  target:
    name: redis-secret-on
    creationPolicy: Owner
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-password
        version: latest
